language: bash
addons:
  apt:
    sources:
    - debian-sid
    packages:

    - 
before_install:
  - sudo apt-get -y --allow-unauthenticated install shellcheck

script:
- shellcheck -a -S warning -s bash ./test/test.sh
- npm run test