language: generic
addons:
  apt:
    sources:
    - debian-sid
    packages:

    - 
before_install:
  - sudo apt-get -y --allow-unauthenticated install shellcheck

script:
- npm run lint
- npm run test